services:
  web:
    build: .
    ports:
      - "2137:2137"
    env_file:
      - .env
    networks:
      - studybuddy

  userio:
    image: lukrzak/userio:1.0
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL:-jdbc:postgresql://swiniak:5432/hackathon-main}
      - DB_USER=${DB_USER:-hackathon}
      - DB_PASS=${DB_PASS:-lecimyniespimy}
    ports:
      - "8080:8080"
    networks:
      - studybuddy
networks:
  studybuddy:
