// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"net/http"
	"web/templates/components"
)

func FriendsPage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>OnlyStudy</title><link rel=\"stylesheet\" href=\"assets/navbar.css\"><link rel=\"stylesheet\" href=\"assets/friends.css\"><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Navbar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container\"><div class=\"friend-view\"><div class=\"friend-info\"><p id=\"name\"><b>Łukasz Nowakowski</b></p><i id=\"trophy-icon\" class=\"fa fa-trophy\" aria-hidden=\"true\"></i><p id=\"score\">65</p></div><div class=\"right-floated\"><p>Last login: 2024-06-16</p><img alt=\"photo\" src=\"/assets/static/1.png\"> <a><i class=\"fa fa-comment\" aria-hidden=\"true\"></i></a> <a><i class=\"fa fa-user-times\" aria-hidden=\"true\"></i></a></div></div><div class=\"friend-view\"><div class=\"friend-info\"><p id=\"name\"><b>Mateusz Naklicki</b></p><i id=\"trophy-icon\" class=\"fa fa-trophy\" aria-hidden=\"true\"></i><p id=\"score\">123</p></div><div class=\"right-floated\"><p>Last login: 2024-06-16</p><img alt=\"photo\" src=\"/assets/static/2.png\"> <a><i class=\"fa fa-comment\" aria-hidden=\"true\"></i></a> <a><i class=\"fa fa-user-times\" aria-hidden=\"true\"></i></a></div></div><div class=\"friend-view\"><div class=\"friend-info\"><p id=\"name\"><b>Tymoteusz Paliński</b></p><i id=\"trophy-icon\" class=\"fa fa-trophy\" aria-hidden=\"true\"></i><p id=\"score\">-1</p></div><div class=\"right-floated\"><p>Last login: 2024-06-16</p><img alt=\"photo\" src=\"/assets/static/3.png\"> <a><i class=\"fa fa-comment\" aria-hidden=\"true\"></i></a> <a><i class=\"fa fa-user-times\" aria-hidden=\"true\"></i></a></div></div><div class=\"friend-view\"><div class=\"friend-info\"><p id=\"name\"><b>Adam Niesiobędzki</b></p><i id=\"trophy-icon\" class=\"fa fa-trophy\" aria-hidden=\"true\"></i><p id=\"score\">997</p></div><div class=\"right-floated\"><p>Last login: 2024-06-15</p><img alt=\"photo\" src=\"/assets/static/4.png\"> <a><i class=\"fa fa-comment\" aria-hidden=\"true\"></i></a> <a><i class=\"fa fa-user-times\" aria-hidden=\"true\"></i></a></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func HandleFriendsPage(w http.ResponseWriter, r *http.Request) {
	FriendsPage().Render(r.Context(), w)
}
