// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"net/http"
	"web/templates/components"
)

func TimeTablePage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><link href=\"https://cdn.rawgit.com/nizarmah/calendar-javascript-lib/master/calendarorganizer.min.css\" rel=\"stylesheet\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Navbar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"calendarContainer\"></div><div id=\"organizerContainer\"></div><script src=\"https://cdn.rawgit.com/nizarmah/calendar-javascript-lib/master/calendarorganizer.min.js\"></script><script>\r\n        var calendar = new Calendar(\"calendarContainer\", \"small\",\r\n                            [ \"Monday\", 3 ],\r\n                            [ \"#ffc107\", \"#ffa000\", \"#ffffff\", \"#ffecb3\" ],\r\n                            {\r\n                                days: [ \"Sunday\", \"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\",  \"Saturday\" ],\r\n                                months: [ \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\", \"August\", \"September\", \"October\", \"November\", \"December\" ],\r\n                                indicator: false,\r\n                                placeholder: \"<span>Custom Placeholder</span>\"\r\n                            });\r\n\r\n        var data = {\r\n                    2017: {\r\n                        12: {\r\n                            25: [\r\n                                {\r\n                                    startTime: \"00:00\",\r\n                                    endTime: \"24:00\",\r\n                                    text: \"Christmas Day\"\r\n                                }\r\n                            ]\r\n                        }\r\n                    }\r\n                };\r\n\r\n        var organizer = new Organizer(\"organizerContainer\", calendar, data);\r\n    </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func HandleTimeTablePage(w http.ResponseWriter, r *http.Request) {
	TimeTablePage().Render(r.Context(), w)
}
